data-service-config:
  host: "0.0.0.0"
  port: 8081
cloud-storage-config:
  api-url-base: https://database.deta.sh/v1
  project-name: ${CLOUD_PROJECT_NAME}
  database-name: ${CLOUD_DATABASE_NAME}
  database-key: ${CLOUD_DATABASE_KEY}